language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then openssl aes-256-cbc -k "$encrypted_key" -in id_rsa.enc -out ~/.ssh/id_rsa -d; chmod 600 ~/.ssh/id_rsa; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then openssl aes-256-cbc -k "$encrypted_key" -in id_pgp.enc -out ~/.gnupg/id_pgp -d; chmod 600 ~/.gnupg/id_pgp; gpg --allow-secret-key-import --import ~/.gnupg/id_pgp; fi
  - git config push.default simple
  - git config commit.gpgsign true
  - git config --global user.email "info@iceframework.org"
  - git config --global user.name "Ice Framework"
  - git config --global user.signingkey 781C2FB7
  - git submodule --quiet update --init --recursive
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then git remote set-url origin git@github.com:ice/framework.git; fi
  - composer install --prefer-source --no-scripts

before_script:
  - ./vendor/phalcon/zephir/install
  - (./vendor/bin/zephir generate; mkdir generated; cp -a ext/. generated)
  - (cd ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall -fvisibility=hidden -DZEPHIR_RELEASE=1"; phpize && ./configure --enable-ice && make -j2 && make install && phpenv config-add ../tests/ci/ice.ini)
  - ulimit -c unlimited || true
  - phpenv config-rm xdebug.ini

script:
  - ./vendor/bin/phpunit --configuration tests/phpunit.xml --testsuite=all

after_failure:
  - gdb -quiet -command=tests/ci/gdb --args $(phpenv which php) vendor/bin/phpunit --debug --colors --configuration tests/phpunit.xml --testsuite=all

after_success:
  - export ZEPHIR_TARGET="legacy"
  - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then export ZEPHIR_TARGET="PHP5"; fi
  - if [[ "$TRAVIS_PHP_VERSION" = "7.0" ]]; then export ZEPHIR_TARGET="PHP7"; fi
  - git checkout $TRAVIS_BRANCH;
  - (mkdir -p build/$ZEPHIR_TARGET; rm -rf build/$ZEPHIR_TARGET/{*,.*})
  - (cp -a generated/. build/$ZEPHIR_TARGET; git add -A build/$ZEPHIR_TARGET)
  - 'echo "$encrypted_key" | git commit -S -m "$ZEPHIR_TARGET, $TRAVIS_COMMIT: regenerate ice sources [ci skip]" build/$ZEPHIR_TARGET'
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$ZEPHIR_TARGET" != "legacy" ]]; then git fetch && git rebase --autostash FETCH_HEAD && git push; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "true" ]]; then git log -1 -p; fi

notifications:
  email:
    - info@iceframework.org

addons:
  apt:
    packages:
      - gdb
      - re2c