language: php
dist: xenial
sudo: required

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: 7.4
    - php: nightly

services:
  - mongodb
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE ice_test;'
  - echo "source tests/ci/ice_test.sql;" | mysql -u root ice_test
  - mongo ice_test --eval 'db.createUser({user:"root",pwd:"password",roles:["readWrite"]});'
  - phpenv config-add tests/ci/mongodb.ini
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then openssl aes-256-cbc -k "$encrypted_key" -in id_rsa.enc -out ~/.ssh/id_rsa -d; chmod 600 ~/.ssh/id_rsa; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then openssl aes-256-cbc -k "$encrypted_key" -in id_pgp.enc -out ~/.gnupg/id_pgp -d; chmod 600 ~/.gnupg/id_pgp; gpg --allow-secret-key-import --import ~/.gnupg/id_pgp; fi
  - git config push.default simple
#  - git config commit.gpgsign true
  - git config --global user.email "info@iceframework.org"
  - git config --global user.name "Ice Framework"
#  - git config --global user.signingkey 781C2FB7
  - git submodule --quiet update --init --recursive
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then git remote set-url origin git@github.com:ice/framework.git; fi
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-source --no-scripts

before_script:
  - (cd vendor/iceframework/zephir-parser; ./install; phpenv config-add tests/ci/zephir_parser.ini)
  - php -d memory_limit=512M ./vendor/bin/zephir generate
  - (mkdir generated; cp -a ext/. generated)
  - (cd ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall -fvisibility=hidden -DZEPHIR_RELEASE=1"; phpize && ./configure --enable-ice && make -j2 && make install && phpenv config-add ../tests/ci/ice.ini)
  - ulimit -c unlimited || true
  - phpenv config-rm xdebug.ini || echo "xdebug not available"

script:
  - ./vendor/bin/phpunit --configuration tests/phpunit.xml --testsuite=all

after_failure:
  - gdb -quiet -command=tests/ci/gdb --args $(phpenv which php) vendor/bin/phpunit --debug --colors --configuration tests/phpunit.xml --testsuite=all

after_success:
  - export ZEPHIR_TARGET="legacy"
  - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then export ZEPHIR_TARGET="php5"; fi
  - if [[ "$TRAVIS_PHP_VERSION" = "7.3" ]]; then export ZEPHIR_TARGET="php7"; fi
  - git checkout $TRAVIS_BRANCH;
  - (rm -rf build/$ZEPHIR_TARGET/; mkdir -p build/$ZEPHIR_TARGET; cp -a generated/. build/$ZEPHIR_TARGET)
  - 'git add -A build/$ZEPHIR_TARGET; git commit -m "$ZEPHIR_TARGET, $TRAVIS_COMMIT: regenerate ice sources [ci skip]" build/$ZEPHIR_TARGET'
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$ZEPHIR_TARGET" != "legacy" ]]; then git fetch && git rebase --autostash FETCH_HEAD && git push; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "true" ]]; then git log -1 -p; fi

notifications:
  email:
    - info@iceframework.org

addons:
  apt:
    packages:
      - gdb
      - re2c